import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {ReactLenis} from "@/utils/lenis"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Athelas - Clone",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} > */}
            <ReactLenis root>
                <body className={` antialiased`} >
                    {children}
                </body>
            </ReactLenis>
        </html>
    );
}
